---
title: "case_study_file"
author: "Binod Jung Bogati"
date: "9/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library(readxl)
library(dplyr)
```


```{r}
province_1 <- read_excel("./data/dengue_np.xlsx", 
                      sheet =1 )

province_2 <- read_excel("./data/dengue_np.xlsx",
                         sheet =2 )
province_3 <- read_excel("./data/dengue_np.xlsx",
                         sheet =3 )
province_4 <- read_excel("./data/dengue_np.xlsx",
                         sheet =4 )
province_5 <- read_excel("./data/dengue_np.xlsx", 
                         sheet =5 )
province_6 <- read_excel("./data/dengue_np.xlsx", 
                         sheet =6 )
province_7 <- read_excel("./data/dengue_np.xlsx",
                         sheet =7 )

nepal_province <- bind_rows(province_1,province_2,province_3,province_4,province_5,province_6,province_7)

```

```{r}
library(tidyverse)
nepal_province
np_province <- nepal_province %>% 
  pivot_longer(data,
               cols =2:8, 
               names_to ="year" , 
               values_to ="cases" )
np_province
```

```{r}
nepal_province %>% View()
np_province %>% View()
```
```{r}
library(purrr)
path<-"./data/dengue_np.xlsx"
province_df<-path %>%
  excel_sheets() %>% 
  set_names() %>% 
map_df(read_excel,
       path=path,
       .id="province")

province_df
  
```
```{r}
province_df
p_df<-province_df %>% 
  pivot_longer(cols=3:9,
               names_to="year",
               values_to="cases")
p_df
```

## Find highest dengue cases in year 2070

```{r}

highest_cases_2070 <- p_df %>% 
 filter(year==2070,cases!=0) %>% 
  select(-year) %>% 
  arrange(desc(cases))
  
  #top 6 cases of dengue
head(highest_cases_2070)
#plotting
highest_cases_2070 %>%#reorder for arranging
ggplot(aes(x=reorder(District,-cases),y=cases,fill=province))+
  geom_bar(stat="identity")+
  labs(title="highest cases of dengue in 2070",
       c="District",
       y="No of cases")+
  coord_flip()+
  theme_minimal()
```
#highest cases of dengue in 2070 by provience

```{r}
highest_cases_2070 <- p_df %>% 
 filter(year==2070,cases!=0) %>% 
  select(-year) %>% 
  arrange(desc(cases))
  
  #plotting
highest_cases_2070 %>%
  group_by(province) %>% 
  summarise(dengue_cases=sum(cases)) %>% 
ggplot(aes(x=reorder(province,dengue_cases),y=dengue_cases,fill=province))+
  geom_col(stat="identity")+
  labs(title="highest cases of dengue in 2070",
       c="District",
       y="No of cases")+
  coord_flip()+
  theme_minimal()
```




## Plot highest cases of 2070

```{r}

highest_cases_2070 

```


```{r}


```

## Convert np_province to wider format

```{r}
dengue_table<- pivot_wider(p_df,
            names_from = "year",
              values_from="cases") %>% 
unnest()#vector list lai seperate garxa
dengue_table
```

```{r}
names(dengue_table)
p_name<-names(dengue_table)[3:9]
dim(dengue_table)
d_table<-dengue_table %>% 
  group_by(province) %>% 
  summarize_at(p_name,sum)

d_table

```











